name: .NET Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Change this to your .NET version

    - name: Restore dependencies
      run: |
          dotnet restore MyConsoleApp/MyConsoleApp.csproj
          dotnet restore MyConsoleApp.Tests/MyConsoleApp.Tests.csproj

    - name: Build
      run: dotnet build MyConsoleApp/MyConsoleApp.csproj --configuration Release

    - name: Test with coverage
      run: |
        dotnet test MyConsoleApp.Tests/MyConsoleApp.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura 
        mv MyConsoleApp.Tests/coverage.cobertura.xml MyConsoleApp.Tests/UnitTestcoverage.cobertura.xml

    - name: Cache coverage report
      uses: actions/cache@v4
      with:
        path: MyConsoleApp.Tests/UnitTestcoverage.cobertura.xml
        key: unit-test-results-${{ github.sha }}
        restore-keys: |
          unit-test-results-
  
    - name: Restore Unit Test coverage report
      uses: actions/cache@v4
      with:
        path: MyConsoleApp.Tests/UnitTestcoverage.cobertura.xml
        key: unit-test-results-${{ github.sha }}
        restore-keys: |
          unit-test-results-
          
    - name: Remove cached artifacts 
      run: |
             gh extension install actions/gh-actions-cache
             REPO=${{ github.repository }}
             BRANCH=${{ github.ref_name }}
             #echo "Fetching list of cache key"
             #cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )
             set +e
             echo $BRANCH
             #for cacheKey in $cacheKeys
             #do
               #echo "Deleting cache key: $cacheKey"
               gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
             #done
             gh actions-cache delete unit-test-results-${{ github.sha }} -R $REPO -B $BRANCH --confirm
             echo "Done"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
