name: .NET Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Change this to your .NET version

    - name: Restore dependencies
      run: |
          dotnet restore MyConsoleApp/MyConsoleApp.csproj
          dotnet restore MyConsoleApp.Tests/MyConsoleApp.Tests.csproj

    - name: Restore dependencies
      run: |
          dotnet restore MyConsoleApp/MyConsoleApp.csproj
          dotnet restore MyConsoleApp.Tests/MyConsoleApp.Tests.csproj

    - name: Build
      run: dotnet build MyConsoleApp/MyConsoleApp.csproj --configuration Release

    - name: Test with coverage
      run: |
        dotnet test MyConsoleApp.Tests/MyConsoleApp.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura 
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"MyConsoleApp.Tests/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:Html
    - name: List coverage files
      run: find . -name 'coverage.cobertura.xml'
      
    - name: Set coverage file path
      id: set-coverage-path
      run: echo "coverage_path=$(find ./MyConsoleApp.Tests/TestResults -name 'coverage.cobertura.xml')" >> $GITHUB_ENV
      
    - name: Generate Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        entryPoint: ${{ env.coverage_path }} # Use the dynamically found path
        badge: false
        fail_below_min: true
        format: text
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: console
        thresholds: 75 
